
version: '3.8'

services:
  # Servicio para desarrollo (entorno anterior)
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Nuevo servicio para producción
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
